<?php
$functions = array(
    'droodle_user_id' => array(         //web service function name
        'classname'   => 'droodle_helpers_external',  //class containing the external function
        'methodname'  => 'user_id',          //external function name
        'classpath'   => 'local/droodle/helpers/externallib.php',  //file containing the class/external function
        'description' => 'Get user id.',    //human readable description of the web service function
        'type'        => 'read',                  //database rights of the web service function (read, write)
    ),
    'droodle_course_id' => array(         //web service function name
        'classname'   => 'droodle_helpers_external',  //class containing the external function
        'methodname'  => 'course_id',          //external function name
        'classpath'   => 'local/droodle/helpers/externallib.php',  //file containing the class/external function
        'description' => 'Get course id.',    //human readable description of the web service function
        'type'        => 'read',                  //database rights of the web service function (read, write)
    ),
    'droodle_list_courses' => array(         //web service function name
        'classname'   => 'droodle_helpers_external',  //class containing the external function
        'methodname'  => 'list_courses',          //external function name
        'classpath'   => 'local/droodle/helpers/externallib.php',  //file containing the class/external function
        'description' => 'List courses',    //human readable description of the web service function
        'type'        => 'read',                  //database rights of the web service function (read, write)
    ),
    'droodle_my_courses' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'my_courses', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user courses', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_info' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_info', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get course info', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_contents' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_contents', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get course topics', 
        'type'        => 'read',                 
    ),
    'droodle_courses_by_category' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'courses_by_category', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get courses from a category', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_categories' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_categories', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get course categories', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_editing_teachers' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_editing_teachers', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get course editing teachers', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_no' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_no', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get number of courses', 
        'type'        => 'read',                 
    ),
    'droodle_get_enrollable_course_no' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_enrollable_course_no', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get number of enrollable courses', 
        'type'        => 'read',                 
    ),
    'droodle_get_student_no' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_student_no', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get number of students', 
        'type'        => 'read',                 
    ),
    'droodle_get_total_assignment_submissions' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_total_assignment_submissions', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get number of submitted assignments', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_students_no' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_students_no', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get number of students in a course', 
        'type'        => 'read',                 
    ),
    'droodle_get_assignment_submissions' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_assignment_submissions', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get course submitted assignments', 
        'type'        => 'read',                 
    ),
    'droodle_get_assignment_grades' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_assignment_grades', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get assignments grades', 
        'type'        => 'read',                 
    ),
    'droodle_get_upcoming_events' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_upcoming_events', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get upcoming events', 
        'type'        => 'read',                 
    ),
    'droodle_get_news_items' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_news_items', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get news', 
        'type'        => 'read',                 
    ),
    'droodle_get_user_grades' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_user_grades', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user grades in a course', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_grade_categories' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_grade_categories', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get  grades categories of course', 
        'type'        => 'read',                 
    ),
    'droodle_search_courses' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'search_courses', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Search courses', 
        'type'        => 'read',                 
    ),
    'droodle_search_categories' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'search_categories', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Search course categories', 
        'type'        => 'read',                 
    ),
    'droodle_search_topics' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'search_topics', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Search course topics', 
        'type'        => 'read',                 
    ),
    'droodle_get_my_courses_grades' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_my_courses_grades', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user grades', 
        'type'        => 'read',                 
    ),
    'droodle_check_moodle_users' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'check_moodle_users', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Check usernames for moodle accounts', 
        'type'        => 'read',                 
    ),
    'droodle_get_moodle_only_users' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_moodle_only_users', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get users existing only in moodle', 
        'type'        => 'read',                 
    ),
    'droodle_get_moodle_users' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_moodle_users', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get moodle users', 
        'type'        => 'read',                 
    ),
    'droodle_get_moodle_users_number' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_moodle_users_number', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get moodle users', 
        'type'        => 'read',                 
    ),
    'droodle_user_exists' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'user_exists', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Check if username exists', 
        'type'        => 'read',                                
    ),
    'droodle_create_user' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'create_user', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Creates user account', 
        'type'        => 'read',                 
    ),
    'droodle_enrol_user' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'enrol_user', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Enrols user into course', 
        'type'        => 'read',                 
    ),
    'droodle_user_details' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'user_details', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user details', 
        'type'        => 'read',                 
    ),
    'droodle_user_details_by_id' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'user_details_by_id', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user details', 
        'type'        => 'read',                 
    ),
    'droodle_migrate_to_droodle' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'migrate_to_droodle', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user details', 
        'type'        => 'read',                 
    ),
    'droodle_my_events' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'my_events', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user events', 
        'type'        => 'read',                 
    ),
    'droodle_delete_user' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'delete_user', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user events', 
        'type'        => 'read',                 
    ),
    'droodle_get_mentees' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_mentees', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user mentees', 
        'type'        => 'read',                 
    ),
    'droodle_get_roles' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_roles', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get roles', 
        'type'        => 'read',                 
    ),
    'droodle_get_parents' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_parents', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get roles', 
        'type'        => 'read',                 
    ),
    'droodle_get_site_last_week_stats' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_site_last_week_stats', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get site stats', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_daily_stats' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_daily_stats', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get course stats', 
        'type'        => 'read',                 
    ),
    'droodle_get_last_user_grades' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_last_user_grades', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get course stats', 
        'type'        => 'read',                 
    ),
    'droodle_system_check' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'system_check', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'droodle system check', 
        'type'        => 'read',                 
    ),
    'droodle_add_parent_role' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'add_parent_role', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Adds parent role', 
        'type'        => 'read',                 
    ),
    'droodle_get_paypal_config' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_paypal_config', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get paypal config', 
        'type'        => 'read',                 
    ),
    'droodle_update_session' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'update_session', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Updates user session', 
        'type'        => 'read',                 
    ),
    'droodle_get_cat_name' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_cat_name', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get category name', 
        'type'        => 'read',                 
    ),
    'droodle_courses_abc' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'courses_abc', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get course list for courses starting with chars', 
        'type'        => 'read',                 
    ),
    'droodle_teachers_abc' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'teachers_abc', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get teachers list for teacher names starting with chars', 
        'type'        => 'read',                 
    ),
    'droodle_teacher_courses' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'teacher_courses', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get courses teached by user', 
        'type'        => 'read',                 
    ),
    'droodle_user_custom_fields' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'user_custom_fields', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get custom fields', 
        'type'        => 'read',                 
    ),
    'droodle_course_enrol_methods' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'course_enrol_methods', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get course available enrolment methods', 
        'type'        => 'read',                 
    ),
    'droodle_quiz_get_question' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'quiz_get_question', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get quiz question', 
        'type'        => 'read',                 
    ),
    'droodle_quiz_get_correct_answer' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'quiz_get_correct_answer', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get quiz question correct answer', 
        'type'        => 'read',                 
    ),
    'droodle_quiz_get_answers' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'quiz_get_answers', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get quiz question answers', 
        'type'        => 'read',                 
    ),
	'droodle_get_course_students' => array(
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_students',
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get course students',
        'type'        => 'read',
    ),
	'droodle_my_teachers' => array(
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'my_teachers',
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user teachers',
        'type'        => 'read',
    ),
	'droodle_my_classmates' => array(
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'my_classmates',
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user classmates',
        'type'        => 'read',
    ),
   'droodle_suspend_enrolment' => array(
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'suspend_enrolment',
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Suspend enrolment',
        'type'        => 'read',
    ),
    'droodle_get_course_resources' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_resources', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get course resources', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_mods' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_mods', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get course mods', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_completion' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_completion', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get course completion', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_quizes' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_quizes', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get course quizes', 
        'type'        => 'read',                 
    ),
    'droodle_my_certificates' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'my_certificates', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user certificates', 
        'type'        => 'read',                 
    ),
    'droodle_get_page' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_page', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get Moodle page', 
        'type'        => 'read',                 
    ),
    'droodle_get_label' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_label', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get Moodle label', 
        'type'        => 'read',                 
    ),
    'droodle_get_news_item' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_news_item', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get Moodle news item', 
        'type'        => 'read',                 
    ),
    'droodle_get_my_news' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_my_news', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user news', 
        'type'        => 'read',                 
    ),
    'droodle_get_my_events' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_my_events', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user events', 
        'type'        => 'read',                 
    ),
    'droodle_get_my_grades' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_my_grades', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get user grades', 
        'type'        => 'read',                 
    ),
    'droodle_quiz_get_random_question' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'quiz_get_random_question', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get random question', 
        'type'        => 'read',                 
    ),
    'droodle_quiz_get_question_categories' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'quiz_get_question_categories', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get  question categories', 
        'type'        => 'read',                 
    ),
    'droodle_multiple_enrol_and_addtogroup' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'multiple_enrol_and_addtogroup', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Enrol user in multiple courses and groups', 
        'type'        => 'read',                 
    ),
    'droodle_multiple_enrol' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'multiple_enrol', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Enrol user in multiple courses', 
        'type'        => 'read',                 
    ),
    'droodle_multiple_suspend_enrolment' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'multiple_suspend_enrolment', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Un-enrol user from multiple courses', 
        'type'        => 'read',                 
    ),
    'droodle_create_droodle_user_additional' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'create_droodle_user_additional', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Creates/updates user account using a different data source', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_grade_categories_and_items' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_grade_categories_and_items', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get  grades categories and  items of course', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_grades_by_category' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_grades_by_category', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get  course grades by category', 
        'type'        => 'read',                 
    ),
    'droodle_get_my_grades_by_category' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_my_grades_by_category', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get  user grades by courses/category', 
        'type'        => 'read',                 
    ),
    'droodle_get_cohorts' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_cohorts', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get  cohorts', 
        'type'        => 'read',                 
    ),
    'droodle_add_cohort_member' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'add_cohort_member', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Add user to cohort', 
        'type'        => 'read',                 
    ),
    'droodle_get_rubrics' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_rubrics', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get assignment rubrics', 
        'type'        => 'read',                 
    ),
    'droodle_get_grade_user_report' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_grade_user_report', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get  user grade report for a course', 
        'type'        => 'read',                 
    ),
    'droodle_get_my_grade_user_report' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_my_grade_user_report', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get  user grade report for all courses', 
        'type'        => 'read',                 
    ),
    'droodle_teacher_get_course_grades' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'teacher_get_course_grades', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get  course grades for teacher', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_groups' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_groups', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get  course groups', 
        'type'        => 'read',                 
    ),
    'droodle_get_group_members' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_group_members', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get  group members', 
        'type'        => 'read',                 
    ),
    'droodle_teacher_get_group_grades' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'teacher_get_group_grades', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get  group grades', 
        'type'        => 'read',                 
    ),
    'droodle_create_course' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'create_course', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Create course', 
        'type'        => 'read',                 
    ),
    'droodle_update_course' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'update_course', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Update course', 
        'type'        => 'read',                 
    ),
    'droodle_add_user_role' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'add_user_role', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Add user role', 
        'type'        => 'read',                 
    ),
    'droodle_get_all_parents' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_all_parents', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get all parent users', 
        'type'        => 'read',                 
    ),
    'droodle_get_course_parents' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_course_parents', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get all parent users of the course', 
        'type'        => 'read',                 
    ),
    'droodle_remove_cohort_member' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'remove_cohort_member', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Remove user from cohort', 
        'type'        => 'read',                 
    ),
    'droodle_multiple_add_cohort_member' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'multiple_add_cohort_member', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Add user to cohorts', 
        'type'        => 'read',                 
    ),
    'droodle_multiple_remove_cohort_member' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'multiple_remove_cohort_member', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Remove user from cohorts', 
        'type'        => 'read',                 
    ),
    'droodle_get_courses_and_groups' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_courses_and_groups', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get courses and their groups', 
        'type'        => 'read',                 
    ),
    'droodle_multiple_enrol_to_course_and_group' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'multiple_enrol_to_course_and_group', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Add user to courses and groups', 
        'type'        => 'read',                 
    ),
    'droodle_multiple_remove_from_group' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'multiple_remove_from_group', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Removes user from groups', 
        'type'        => 'read',                 
    ),
    'droodle_my_all_courses' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'my_all_courses', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get all users in which the has a role assgined', 
        'type'        => 'read',                 
    ),
   'droodle_unenrol_user' => array(
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'unenrol_user',
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Unenrol user',
        'type'        => 'read',
    ),
   'droodle_multiple_unenrol_user' => array(
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'multiple_unenrol_user',
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Multiple unenrol user',
        'type'        => 'read',
    ),
    'droodle_get_children_grades' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_children_grades', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get children grades', 
        'type'        => 'read',                 
    ),
    'droodle_get_children_grade_user_report' => array(        
        'classname'   => 'droodle_helpers_external',
        'methodname'  => 'get_children_grade_user_report', 
        'classpath'   => 'local/droodle/helpers/externallib.php',
        'description' => 'Get children grade report', 
        'type'        => 'read',                 
    ),
);

?>
